### ISSUE TITLE
Change labels of some packages

### ISSUE THREAD

**Issue by theroggy** [conda-forge/geofileops-feedstock#12]
@conda-forge/core : 

I applied incorrect labels on some packages. Would it be possible to change them for me?

These should get the 'geofileops_rc' label instead of the current one:
* https://anaconda.org/conda-forge/geofileops/0.2.2rc0/download/noarch/geofileops-0.2.2rc0-pyhfb930a1_1.tar.bz2
* https://anaconda.org/conda-forge/geofileops/0.2.2rc0/download/noarch/geofileops-0.2.2rc0-pyhd8ed1ab_0.tar.bz2

These should get the 'geofileops_dev' label instead of the current one:
* https://anaconda.org/conda-forge/geofileops/0.2.2b2/download/noarch/geofileops-0.2.2b2-pyhd8ed1ab_0.tar.bz2
* https://anaconda.org/conda-forge/geofileops/0.2.2b1/download/noarch/geofileops-0.2.2b1-pyhd8ed1ab_0.tar.bz2
* https://anaconda.org/conda-forge/geofileops/0.2.2a2/download/noarch/geofileops-0.2.2a2-pyhd8ed1ab_0.tar.bz2
* https://anaconda.org/conda-forge/geofileops/0.2.1a5/download/noarch/geofileops-0.2.1a5-pyhd8ed1ab_0.tar.bz2
* https://anaconda.org/conda-forge/geofileops/0.2.1a1/download/noarch/geofileops-0.2.1a1-pyhd8ed1ab_0.tar.bz2

Thanks!!!

**Comment by isuruf** [comment]
Done
