### ISSUE TITLE
Change labels of some packages

### ISSUE THREAD

**Issue by theroggy** [conda-forge/geofileops-feedstock#24]
@conda-forge/core :

I applied incorrect labels on some packages :-(. Would it be possible to change them for me?

These should get the 'geofileops_dev' label instead of the current one:

- https://anaconda.org/conda-forge/geofileops/0.3.1b1/download/noarch/geofileops-0.3.1b1-pyh6b7fa68_1.tar.bz2
- https://anaconda.org/conda-forge/geofileops/0.3.1b1/download/noarch/geofileops-0.3.1b1-pyhd8ed1ab_0.tar.bz2

Thanks!!!

**Comment by ocefpaf** [comment]
Done. Can you check if that is correct?

**Comment by theroggy** [comment]
Perfect, thanks!!!
